### ISSUE TITLE
Please include your live site

### ISSUE THREAD

**Issue by gcarreno** [Noleli/EncodeMightyThings#2]
Hi Noleli(@Noleli),

Could you please include `https://projects.noahliebman.net/encodemightythings/` on your `README.md` as to point to a live version of this body of work?

Many thanks!!

Cheers,
Gus

**Comment by Noleli** [comment]
Done, thanks for the nudge!

**Comment by gcarreno** [comment]
Hey Noleli(@Noleli),

No probs whatsoever!!

Thanks!! :hugs: 

Cheers,
Gus
